#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  # formatter: html
  # # Output file instead of logging results
  # output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: './_sass/*.s+(a|c)ss'
  ignore:
    - '/vendor'
# Rule Configuration
rules:
  final-newline: 
    - 2
    - 
      include: false
  placeholder-in-extend: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  trailing-semicolon: 
    - 2
    - 
      include: true
  property-units: 
    - 2
    - 
      global: ['rem']
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  hex-length: 
    - 2
    -
      style: long
  hex-notation:
    - 2
    -
      style: uppercase
