language: ruby
rvm:
  - 2.4.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:  
- bundle exec rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: 
- bundler # caching bundler gem packages will speed up build
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false


cache:
